rm(list=ls())
setwd("~/Documents/integr8_genom/Miner/miner_results/yeast/OVERLAPS/")
#data <- read.table("./mergedeffect/results_yeast_cmonkey_1_expr_MSEC_KendallC_GEECE_refine12345_top_0.25_1.0_c_liven_reconstructed_pval0.001_cut_0.01_member_graph_overlap_TOTAL.eda_toplist_mergedeffect.txt",sep="\t",header=F)
data <- read.table("./mergedeffect/results_yeast_cmonkey_1_expr_MSEC_KendallC_GEECE_refine12345_top_0.25_1.0_c_liven_reconstructed_pval0.001_cut_0.01_member_graph_overlap_TOTAL.eda_toplist_mergedeffect_min.txt",sep="\t",header=F)



hist(data[,2])
plot(data[,2], data[,3]/data[,6])
overlaps <- read.table("../EXPR_round12345_merge_refine/results_yeast_cmonkey_1_expr_MSEC_KendallC_GEECE_refine12345_top_0.25_1.0_c_liven_reconstructed_pval0.001_cut_0.01_member_graph_overlap_TOTAL.eda",sep="\t",header=F)
head(overlaps)
overlaps <- read.table("../EXPR_round12345_merge_refine/results_yeast_cmonkey_1_expr_MSEC_KendallC_GEECE_refine12345_top_0.25_1.0_c_liven_reconstructed_pval0.001_cut_0.01_member_graph_overlap_TOTAL.eda",sep=" = ",header=T)
overlaps <- read.table("../EXPR_round12345_merge_refine/results_yeast_cmonkey_1_expr_MSEC_KendallC_GEECE_refine12345_top_0.25_1.0_c_liven_reconstructed_pval0.001_cut_0.01_member_graph_overlap_TOTAL.eda",sep=""=",header=T)
getwd()
overlaps <- read.table("./overlaps_simple.txt"sep="\t",header=F)
overlaps <- read.table("./overlap_simple.txt"sep="\t",header=F)
overlaps <- read.table("./overlaps_simple.txt",sep="\t",header=F)
overlaps <- read.table("./overlap_simple.txt",sep="\t",header=F)
hist(overlaps)
sum(overlaps > 0.25)
sum(overlaps)
length(overlaps)
dim(overlaps)
1867/17030
plot(data[,2], data[,3]/data[,6])
plot(data[,2], data[,3]/data[,6],xlab="Score ratio",ylab="Overlap fraction")
sum(data[,2] > )
sum(data[,2] > 1)
sum(data[,2] < 1)
10434/17030
data <- read.table("./mergedeffect/results_yeast_cmonkey_1_expr_MSEC_KendallC_GEECE_refine12345_top_0.25_1.0_c_liven_reconstructed_pval0.001_cut_0.01_member_graph_overlap_TOTAL.eda_toplist_mergedeffect.txt",sep="\t",header=F)
head(data)
plot(data[,2], data[,3]/data[,6])
plot(data[,2], data[,3]/data[,6])
data <- read.table("./mergedeffect/results_yeast_cmonkey_1_expr_MSEC_KendallC_GEECE_refine12345_top_0.25_1.0_c_liven_reconstructed_pval0.001_cut_0.01_member_graph_overlap_TOTAL.eda_toplist_mergedeffect.txt",sep="\t",header=F)
plot(data[,2], data[,3]/data[,6])
plot(data[,2], data[,3]/data[,6], ylim=c(0.95, 1.1))
plot(data[,2], data[,3]/data[,6], xlim=c(0.95, 1.1))
plot(data[,2], data[,3]/data[,6], xlim=c(0.95, 1.05))
plot(data[,2], data[,3]/data[,6], xlim=c(0.95, 1.01))
sum(data[,2] > 1)
plot(data[,2], data[,3]/data[,6], xlim=c(0.95, 1.0))
plot(data[,2], data[,3]/data[,6], xlim=c(0.95, 1.0), xlab="Score ratio (merged/mean)", ylab="overlap ratio")
which(data[,2] < 0.98 & data[,3]/data[,6])
plot(data[,2], data[,3]/data[,6], xlim=c(0.95, 1.0))
plot(data[,2], data[,3]/data[,6], xlim=c(0.95, 1.0), xlab="Score ratio (merged/mean)", ylab="overlap ratio")
plot(data[,8], data[,9])
plot(data[,9], data[,8])
plot(data[,9], data[,8], xlab="Score ratio (merged/mean)", ylab="overlap ratio")
plot(data[,9], data[,8], xlab="Score ratio (merged/mean)", ylab="overlap ratio (intersection/merged)")
plot(data[,9], data[,8], xlab="Score ratio (merged/mean)", ylab="overlap ratio (intersection/merged)")
which(data[,9] < 1 && data[,8] > 0.2)
which(data[,9] < 1 & data[,8] > 0.2)
which(data[,9] < 0.99 & data[,8] > 0.2)
which(data[,9] < 0.999 & data[,8] > 0.2)
which(data[,9] < 0.998 & data[,8] > 0.2)
which(data[,9] < 0.997 & data[,8] > 0.2)
which(data[,9] < 0.98 & data[,8] > 0.1)
data[2095,1]
data[2599,1]