setwd("/Users/mjoachimiak/Documents/integr8_genom/Miner/miner_results/")
source("ROC_analysis_ALL_methods.R")
setwd("/Users/mjoachimiak/Documents/integr8_genom/Miner/miner_results/ROC_r_incr_nono_pG/")
pdf("r_incr_nono_pG_g_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "g")
doCase("true2", "g")
doCase("true3", "g")
doCase("true4", "g")
dev.off(2)
	
pdf("r_incr_nono_pG_e_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "e")
doCase("true2", "e")
doCase("true3", "e")
doCase("true4", "e")
dev.off(2)

pdf("r_incr_nono_pG_ge_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "ge")
doCase("true2", "ge")
doCase("true3", "ge")
doCase("true4", "ge")
dev.off(2)


setwd("/Users/mjoachimiak/Documents/integr8_genom/Miner/miner_results/")
source("ROC_analysis_ALL_methods.R")
setwd("/Users/mjoachimiak/Documents/integr8_genom/Miner/miner_results/ROC_r_incr_nono_pG_batch_metro/")
pdf("r_incr_nono_pG_batch_metro_g_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "g")
doCase("true2", "g")
doCase("true3", "g")
doCase("true4", "g")
dev.off(2)
	
pdf("r_incr_nono_pG_batch_metro_e_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "e")
doCase("true2", "e")
doCase("true3", "e")
doCase("true4", "e")
dev.off(2)

pdf("r_incr_nono_pG_batch_metro_ge_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "ge")
doCase("true2", "ge")
doCase("true3", "ge")
doCase("true4", "ge")
dev.off(2)


setwd("/Users/mjoachimiak/Documents/integr8_genom/Miner/miner_results/")
source("ROC_analysis_ALL_methods.R")
setwd("/Users/mjoachimiak/Documents/integr8_genom/Miner/miner_results/ROC_r_incr_nono_pG_batch_metro_rand/")
pdf("r_incr_nono_pG_batch_metro_rand_g_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "g")
doCase("true2", "g")
doCase("true3", "g")
doCase("true4", "g")
dev.off(2)
	
pdf("r_incr_nono_pG_batch_metro_rand_e_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "e")
doCase("true2", "e")
doCase("true3", "e")
doCase("true4", "e")
dev.off(2)

pdf("r_incr_nono_pG_batch_metro_rand_ge_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "ge")
doCase("true2", "ge")
doCase("true3", "ge")
doCase("true4", "ge")
dev.off(2)


setwd("/Users/mjoachimiak/Documents/integr8_genom/Miner/miner_results/")
source("ROC_analysis_ALL_methods.R")
setwd("/Users/mjoachimiak/Documents/integr8_genom/Miner/miner_results/ROC_r_incr_nono_rand_pG_metro/")
pdf("r_incr_nono_rand_pG_metro_g_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "g")
doCase("true2", "g")
doCase("true3", "g")
doCase("true4", "g")
dev.off(2)
	
pdf("r_incr_nono_rand_pG_metro_e_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "e")
doCase("true2", "e")
doCase("true3", "e")
doCase("true4", "e")
dev.off(2)

pdf("r_incr_nono_rand_pG_metro_ge_allcrit.pdf",width=8,height=11)
par(mfrow=c(2,2))
doCase("true1", "ge")
doCase("true2", "ge")
doCase("true3", "ge")
doCase("true4", "ge")
dev.off(2)
